### ISSUE TITLE
Problem dealing with wallet transfers

### ISSUE THREAD

**Issue by sophom** [robertwb/bitcoin-taxes#4]
Hello,

The code seems to have a problem with an internal transfer. I transferred btc from a bitcoin-qt wallet to an electrum wallet. I run the script as follows:

`./bitcoin_gains.py --consolidate_bitcoind bitcoin-qt_2017.json electrum_2017.csv 
`
The error I get look like this: 

```
Traceback (most recent call last):
  File "./bitcoin_gains.py", line 1354, in <module>
    main(parsed_args)
  File "./bitcoin_gains.py", line 1226, in main
    lost_in_transfer -= lost.btc
AttributeError: 'NoneType' object has no attribute 'btc'
```
Please let me know if you need me to try a fix.

**Comment by robertwb** [comment]
That'd be great if you could try your hand at fixing this.

**Comment by sophom** [comment]
I was hoping you could come up with a fix that I would try but OK I'll give it a shot. I haven't looked at the code in a couple of years so I'll need to refamiliarize myself with it.

**Comment by sophom** [comment]
Hey does this make sense?

```
➜  bitcoin-taxes git:(master) ✗ git diff bitcoin_gains.py
diff --git a/bitcoin_gains.py b/bitcoin_gains.py
index 98e3c5f..0158e64 100755
--- a/bitcoin_gains.py
+++ b/bitcoin_gains.py
@@ -1257,7 +1257,8 @@ def main(args):
                 if t.type == 'transfer':
                     if lost_in_transfer:
                         lost, buy = buy.split(lost_in_transfer)
-                        lost_in_transfer -= lost.btc
+                        if lost:
+                            lost_in_transfer -= lost.btc
                     if buy:
                         push_lot(t.dest_account, buy)
                         account_btc[t.dest_account] += buy.btc

```

**Comment by robertwb** [comment]
Yes, I think so. Can you provide a (possibly anonymized) example that
triggers this?

**Comment by sophom** [comment]
Anonymizing the example seems difficult since we look up the txid. I did the next best thing I could think of. I picked a random transaction from the block chain and recreated the bitcoin-qt and electrum output files. I have the files attached. They expose the problem without the above fix. Applying the fix seems to work.
[testcase_wallet_merge.tar.gz](https://github.com/robertwb/bitcoin-taxes/files/1584911/testcase_wallet_merge.tar.gz)

**Comment by sophom** [comment]
Hey... I can't create a branch with the fix... Can you allow me?

**Comment by robertwb** [comment]
Sorry for the slow fix on this--been out for the holidays. Could you try forking and making a pull request?

**Comment by robertwb** [comment]
Thanks.
