### ISSUE TITLE
Transfers from Coinbase to public address not "matched"

### ISSUE THREAD

**Issue by cbmartin** [robertwb/bitcoin-taxes#5]
Several transfers listed in a Coinbase csv file were not matched in the list of transactions derived from a list of public addresses.  The result is that several transfers from Coinbase to my public address are incorrectly identified as external transactions.

It appears that the BTC amount reported by Coinbase and the amount actually transferred into my public address do not match exactly.  For example, the Coinbase csv file reports one transfer of the amount -0.85301237 BTC, but the actual amount transferred to my public address was 0.8530 BTC.  The Coinbase csv file reports the transaction hash in the last column which I can use to confirm the discrepancy between amounts.  As a workaround, I have manually edited my Coinbase csv file to split each misidentified transaction into one amount which matches excactly the amount in the public bitcoin transaction, and one additional transaction for the remaining amount which will be categorized as an expense.

**Comment by robertwb** [comment]
Please give this a try. If this doesn't work, some samples would be helpful.

**Comment by cbmartin** [comment]
(I wasn't really expecting a reply to my issue, just hoping to document my workaround in case others find the same problem...  but since you're working on it see the following)

I get a global name is not defined error when testing your new version as follows. See attached for test input files which replicate the issue.
[addresses-test.txt](https://github.com/robertwb/bitcoin-taxes/files/1584188/addresses-test.txt)
[Coinbase-test.csv.txt](https://github.com/robertwb/bitcoin-taxes/files/1584196/Coinbase-test.csv.txt)


```
./bitcoin_gains.py Coinbase-test.csv.txt addresses-test.txt 
Coinbase-test.csv <__main__.CoinbaseParser object at 0x1036de750>
addresses-test.txt <__main__.AddressListParser object at 0x1036de5d0>
detected transfer: withdraw(2015-08-10 02:05:56, 0, -0.001, Coinbase-test.csv, txid=089afd...) + deposit(2015-08-09 20:05:56, 0, 0.00100000, addresses-test.txt, txid=089afd...) -> transfer(2015-08-10 02:05:56, 0, -0.001, Coinbase-test.csv, dest=addresses-test.txt)
no match on amount withdraw(2015-09-26 08:31:10, 0, -0.00010000, addresses-test.txt, txid=b6ca97...) [deposit(2015-08-10 10:44:20, 0, 0.00010000, addresses-test.txt, txid=53e275...), deposit(2015-10-26 15:41:22, 0, 0.00010000, addresses-test.txt, txid=a8d872...)]
Traceback (most recent call last):
  File "./bitcoin_gains.py", line 1388, in <module>
    main(parsed_args)
  File "./bitcoin_gains.py", line 1070, in main
    candidate = txid_matches
NameError: global name 'txid_matches' is not defined
```

**Comment by robertwb** [comment]
Sorry, there was a typo. Try it now.
